### PR TITLE
Rename coala-analyzer to coala

### PR DESCRIPTION
**Pull request by simobasso**

### CODE REVIEW

**Comment by arafsheikh** [comment]
@AbdealiJK Tests fail for some reason. Please have a look.

**Comment by sils** [comment]
@arafsheikh can you investigate? The changes itself seem rather sane.

**Comment by sils** [comment]
commit messages don't comply to coala.io/commits yet. I've set up gitmate for this repo so it'll appear in our reviewers todo list when updated next time.

**Comment by sils** [comment]
tests fail also in https://github.com/coala/coala-atom/pull/22 - it's not a fault of this PR. Marking pending review so someone with more knowledge of this plugin looks at it.

**Comment by sils** [comment]
CC @AbdealiJK

**Comment by AbdealiLoKo** [comment]
I believe that the plugin doesn't work with the latest atom version. Which causing this to fail.
Needs more investigation

**Comment by AbdealiLoKo** [comment]
Merging this as the fail is unrelated.
@rultor merge

**Comment by AbdealiLoKo** [comment]
@rultor merge

**Comment by AbdealiLoKo** [comment]
@rultor merge

**Comment by AbdealiLoKo** [comment]
@rultor merge

**Pull request merged**
