### PR TITLE
readme: added inline link to the 'linter'

### PR DESCRIPTION
**Pull request by ed4140**
Closes https://github.com/coala/coala-atom/issues/49

### CODE REVIEW

**Comment by RohanVB** [comment]
circleci is failing here. 
https://circleci.com/gh/coala/coala-atom/72?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
pip install --pre -U coala-bears returned exit code 2

Action failed: pip install --pre -U coala-bears
```
https://docs.coala.io/en/latest/Users/Exit_Codes.html

**Comment by ed4140** [comment]
Yes, but only `README.md `was changed, so i think the problem is somewhere else

**Comment by RohanVB** [comment]
Merging since circleci issue is unrelated to readme changes.
(Also, previous history shows we don't enforce strict commit guidelines in this repo)

**Comment by RohanVB** [comment]
@rultor merge

**Pull request merged**
