### PR TITLE
Sils/assemble

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by jayvdb** [comment]
I find the commit message of 25f6534e5117 "actually made the whole thing not work" to be lacking public analysis to back up that statement, and it is not a good statement to include in a permanent commit log without evidence.

**Comment by sils** [comment]
ack https://github.com/coala/coala-atom/pull/34/commits/b64e4a5074e00b7936b729851f05d44885e3746f https://github.com/coala/coala-atom/pull/34/commits/a609cb692c20a0f0907a1f5701f6e2ba9344dc80

(Since those are not my commits)

**Comment by sils** [comment]
a609cb6 ack

**Comment by Nosferatul** [comment]
ack 081c2c7

**Comment by Nosferatul** [comment]
ack 36c627c 73729c7

**Comment by sims1253** [comment]
@rultor merge

**Comment by sils** [comment]
24ece1b wasn't acked yet

**Comment by sils** [comment]
@sims1253 please check 24ece1b and we can revert the commit if something's wrong

**Comment by sims1253** [comment]
oh no gitmate :scream:

**Comment by sims1253** [comment]
ack 24ece1b8a5d919864cdc2ef6d6844b54f0d95aca

looks sane

**Pull request merged**
