### PR TITLE
README.md: Add alternative method for installation

### PR DESCRIPTION
**Pull request by kaustubhhiware**
README.md: Add alternative method for installation

Alternative method involves manual `git clone`, and `npm install`

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala-atom/pull/58/commits/cacc2604fbd55b81aada3558ad37565dfc138e84

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

**Comment by kaustubhhiware** [comment]
Thanks ! Actually, this is my second :sweat_smile:.

**Pull request merged**
