### PR TITLE
The bug was in the regex, now it seems to be parsing issues properly

### PR DESCRIPTION
**Pull request by alexandruionascu**

### CODE REVIEW

**Comment by jayvdb** [comment]
I've build a patch to work around most of the circle build problems. See https://github.com/coala/coala-atom/pull/27

When I add it to your patch, there are still errors in the tests.  See https://circleci.com/gh/coala/coala-atom/40

**Comment by sils** [comment]
also see coala.io/commit for commit message guidelines

**Comment by sils** [comment]
We should check if there's an issue connected to this. @alexandruionascu do you intend to update this?

**Comment by sils** [comment]
I pulled this into https://github.com/coala/coala-atom/pull/34 as it's needed *together with other PRs* to get the tests passing

**Pull request closed without merging**
