### PR TITLE
main.coffee: Update coala version

### PR DESCRIPTION
**Pull request by RohanVB**

### CODE REVIEW

**Comment by supergr35** [comment]
de83b28 is ready

**Review by EverWinter23 — APPROVED** [review]

**Review by EverWinter23 — APPROVED** [review]

**Comment by RohanVB** [comment]
Sorry I didn't notice that I had a PR on this before opening the issue.

**Comment by EverWinter23** [comment]
So, is this issue closed?
Or should i still keep working on it?But, I haven't been assigned to this issue.

**Comment by RohanVB** [comment]
You have to join the coala org before getting assigned to an issue. I mentioned how to on your latest PR. If you'd still like to work on it, let me know. Ill reopen the issue and close this PR :)
@EverWinter23

**Comment by EverWinter23** [comment]
I have joined coala org. And yes I would like to work on it.

**Pull request closed without merging**
