### PR TITLE
Add CI and clean up code

### PR DESCRIPTION
**Pull request by AbdealiLoKo**
- Use existing functions to make our code simpler.
- Add circleci testing
- make the code more coffee-ish
- Add ranges instead of just the first line

### CODE REVIEW

**Comment by sils** [comment]
ack 3a61d41 52a8d77 27510c0 8b5672c

**Comment by sils** [comment]
Hey, sometimes I seem to get results for the wrong file:

screenshot from 2016-02-08 08-01-58

**Comment by AbdealiLoKo** [comment]
Don't merge yet

-----Original Message-----

**Comment by sils** [comment]
What's missing?

**Comment by AbdealiLoKo** [comment]
@rultor merge

**Comment by AbdealiLoKo** [comment]
That's interesting.
I do not think that's a wrong result.
That part of the coffee code defines a json (like defining a python dictionary).
So atom finds embedded json and gives that to

-----Original Message-----

**Pull request merged**
