### PR TITLE
.coafile:Add YAMLLintBear #71

### PR DESCRIPTION
**Pull request by shivasv97**
Add YAMLLintBear for fixing issues with .yml files.

### CODE REVIEW

**Review by yashovardhan — CHANGES_REQUESTED** [review]
LGTM, but add the issue name in the description so that it closes the issue when PR is merged.

Also kindly assign yourself to this issue via gitter
as you have given the PR but not have been assigned an issue. 

Enjoy the experience of contributing in coala 😄

**Comment by Makman2** [comment]
Please adhere to our commit guidelines, you can find them with our newcomer guide. There are similar commits whose messages you can reuse in e.g. our `coala/coala`-repo :+1:

**Comment by shivasv97** [comment]
Yes, I shall make the required changes and adhere to the guidelines. Thanks for your replies. :)

**Comment by aashutoshrathi** [comment]
Please close this PR.

**Comment by Makman2** [comment]
Closing due to inactivity and unassignment.

**Pull request closed without merging**
