### PR TITLE
readme fix for MarkdownBear

### PR DESCRIPTION
**Pull request by khushmeeet**
README.md: Change file for MarkdownBear

README.md is changed so that correct formatting is done by MarkdownBear

Closes https://github.com/coala/coala-atom/issues/29

### CODE REVIEW

**Comment by Udayan12167** [comment]
Please reference the issue that you are fixing. i.e in the commit message `Closes <issue-link>`.

**Comment by Udayan12167** [comment]
Your commit message is not the correct format it should be `<Filename>: Description of commit.`

**Comment by Udayan12167** [comment]
This link should help you http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by khushmeeet** [comment]
Thanks for pointing that out!

**Comment by RohanVB** [comment]
@Khushmeet ping on gitter if you need help with this :)

**Comment by adtac** [comment]
@Khushmeet need help with the PR? Stuck somewhere? Just pop in and say hello in our chat: http://coala.io/chat

Your commit message needs a little bit of work. You can find the guidelines here: http://coala.io/commit

**Comment by adtac** [comment]
Closing and unassigning due to inactivity for over a month.

**Pull request closed without merging**
